title: "Poonam's Blog"
author: "Poonam Parhar"
description: "A place to share my troubleshooting and debugging experience with Java and JVM

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
# email: "poonam"
twitter_username: "poonambajaj"
github_username: "poonamparhar"
linkedin_username: "poonam"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################

remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
rss: rss

theme: "modernist"

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
